config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'cleans/sindan' => 'cleans#sindan'
  get 'cleans/kensaku' => 'cleans#kensaku'
  get 'users/show/iine/:id', to: 'users#iine'
  get 'cleans/gaiyou' => 'cleans#gaiyou'

  resources :cleans do

    post 'kensaku', on: :collection
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  
  resources :users, only: [:show, :iine]
  root 'cleans#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clean.rb
class Clean < ApplicationRecord
    belongs_to :user

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    has_many :clean_tags, dependent: :destroy
    has_many :tags, through: :clean_tags
    mount_uploader :image, ImageUploader
end

app/models/clean_tag.rb
class CleanTag < ApplicationRecord
  belongs_to :clean
  belongs_to :tag
end

app/models/clean_tag2.rb
class CleanTag2 < ApplicationRecord

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :clean
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :cleans
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :clean_tags, dependent: :destroy
    has_many :clean, through: :clean_tags
end

app/models/tag2.rb
class Tag2 < ApplicationRecord
    has_many :clean_tag2s, dependent: :destroy
    has_many :cleans, through: :clean_tag2s
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
    has_many :cleans, dependent: :destroy
    validates :name, presence: true
    validates :profile, length: { maximum: 200 }
    has_many :cleans, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_cleans, through: :likes, source: :clean
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
  def already_liked?(clean)
    self.likes.exists?(clean_id: clean.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
    end
    
end

app/controllers/cleans_controller.rb
class CleansController < ApplicationController

    before_action :authenticate_user!, only: [:new, :create]
    
    def index
    end

    def sindan
    end

    def kensaku

      if params[:search] == nil

        @cleans = Clean.all

      elsif params[:search] == ''

        @cleans = Clean.all

      else

        @cleans = Clean.where("maker LIKE ? OR name LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%")
      end
    end

    def new

      @clean = Clean.new
    end
  
    def create

      clean = Clean.new(clean_params)
      clean.user_id = current_user.id

      if clean.save

        Rails.logger.info "投稿成功"
        redirect_to :action => "kensaku"

      else

        Rails.logger.info "投稿失敗"
        redirect_to :action => "new"
      end
    end

    def show

      @clean = Clean.find_by(id: params[:id])

      if @clean

        @comments = @clean.comments
        @comment = Comment.new

      else
        redirect_to cleans_path, alert: "投稿が見つかりませんでした"
      end
    end

    def destroy

      clean = Clean.find(params[:id])

      redirect_to action: :kensaku
      clean.destroy
    end
    
    private
    def clean_params

      params.require(:clean).permit(:maker, :genre, :cost, :name, :about, :image, :overall, :light, :power, :care, :time, :tag_ids)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create

        clean = Clean.find(params[:clean_id])
        comment = clean.comments.build(comment_params)
        comment.user_id = current_user.id

        if comment.save

            flash[:success] = "コメントしました"
            redirect_back(fallback_location: root_path)

        else

            flash[:success] = "コメントできませんでした"
            redirect_back(fallback_location: root_path)
        end
    end

    private
    def comment_params
        
        params.require(:comment).permit(:content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create

        like = current_user.likes.create(clean_id: params[:clean_id])
        redirect_back(fallback_location: root_path)
    end

    def destroy

        like = Like.find_by(clean_id: params[:clean_id], user_id: current_user.id)
        
        like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show

        @user = User.find(params[:id]) 
        @clean = Clean.all
    end

    def iine
        
        @user = User.find(params[:id]) 
        @cleans = Clean.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clean_helper.rb
module CleanHelper
    def getPercent(number) 
        if number.present?
            calPercent = number/5.to_f * 100
            # calPercent = number/10.to_f * 100
            #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
            percent = calPercent.round
            #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
            return percent.to_s
        else
            return 0
        end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cleans/index.html.erb
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="./stylesheets/index.css">
  </head>
  
  <body>
    <section id="first-block">
      <div class="top-block">CLEAN <span>UP</span></div>
    </section>
      
    <script src="test.js"></script>

    <section id="second-block">
      <p class="info-title">
        種類は大きく分けて３種類
        <br></br>
      </p>
      <div class="about-container">
        <p class="info-text">
          <b>サイクロン式</b>
          <br></br>
          <span class="font-small">
            <br>
            遠心力によって吸ったゴミと空気を分離し、容器内にゴミを溜め込み、都度捨てる掃除機タイプ。
            <br>
            <br>
            容器、フィルター等の手入れが必要ではあるが、ランニングコストがかからず何度でも使用可能。
            <br>
            <br>
            欠点である手入れの手間を極限まで省いた、
            <br>
            ”フィルターレスサイクロン式”も存在する。
          </span>
        </p>
        <p class="info-text">
          <b>紙パック式</b>
          <br></br>
          <span class="font-small">
            <br>
            吸ったゴミを紙パックにため込む掃除機タイプ。交換頻度は機種によりけりだが平均月1交換。
            <br>
            <br>
            パック交換のコストはかかるが、毎度のゴミ捨て不要。満杯になり次第交換のため手入れも不要。
            <br>
            <br>
            サイクロン式に比べ、手入れ不要という魅力点
            <br>
            から近頃は紙パック式の機種が増加傾向。
          </span>
        </p>
        <p class="info-text">
          <b>クリーンベース式</b>
          <br></br>
          <span class="font-small">
          <br>
            サイクロン式同様容器にゴミを溜め、本体を充電ドックに戻すとゴミを吸引、ドック内に溜める。
            <br>
            <br>
            面倒な毎度のゴミ捨てを無くし、コストもかからない最新式。ドック内のゴミは月1で処理する。
            <br>
            <br>
            毎度のゴミ捨ての手間を省いた最新式。ドック内はサイクロンと紙パックの両タイプが存在する。
          </span>
        </p>
      </div>
    </section>

    <section id="third-block">
      <p class="events-title">
        スティッククリーナーの選び方
      </p>
      <div class="event-container">
        <div class="event">
        <%= image_tag 'pork.png', class:'powerorkarusa' %>
          <p class="event-name">
            <span>重視すべきは...パワー? 軽さ? </span>
            <br>
            <br>
            <br>
            当然「軽い」ということは、バッテリーやモーター、<br>
            <br>
            ヘッドが軽量化されているため吸引力は落ちる。<br>
            <br>
            逆も然り。自分にちょうどいい重さを見つけることが理想だ。<br>
            <br>
            軽さ”だけ”、パワー”だけ” で選ぶと<br>
            <br>
            失敗する可能性がある事を覚えておこう。<br>
          </p>
        </div>
        <div class="event">
          <p class="event-name">
            <span>運転時間の確認</span>
            <br>
            <br>
            <br>
            10分程の機種から60分以上稼働できる機種まで様々存在する。<br>
            <br>
            また、記載の時間は”弱モード”使用時の記載であることが多く、<br>
            <br>
            ”強モード”での使用は5～10分の機種が殆ど。<br>
            <br>
            購入前に確認しておく必要がある。<br>
          </p>
          <%= image_tag 'time.webp', class:'time-image' %>
        </div>
        <div class="event">
        <%= image_tag 'kegarami.jpg', class:'kegarami' %>
          <p class="event-name">
            <span>ペット対応している？</span>
            <br>
            <br>
            <br>
            ブラシには種類があり、ペット毛が巻き付くブラシもある。<br>
            <br>
            巻きついてしまうと、その分の手入れや故障のリスクがある。<br>
            <br>
            ペットを飼っている方は、対応のブラシ搭載機種を選択しよう。<br>
            <br>
            このサイトではペット毛対応か否かを記載しているため<br>
            <br>
            1つの指標として参考にしてほしい。<br>
          </p>
        </div>
        <div class="event">
          <p class="event-name">
            <span>手入れの確認</span>
            <br>
            <br>
            <br>
            掃除機選びの際意外と見落としがちなのが手入れである。<br>
            <br>
            どのパーツをどのように、どのくらいの頻度で手入れするか確認しよう。<br>
            <br>
            手入れが面倒な方は、”フィルターレス”に注目するのもアリ。<br>
            <br>
            最近では、紙パック式も登場しているので、<br>
            <br>
            気になる方はチェックしてみよう。<br>
          </p>
          <%= image_tag 'teire.jpg', class:'teire' %>
        </div>
      </div>
      <div class="gosindan">
        <p>結局自分にはどんな機種が合うんだろう...?</p>
        <br>
        <p>そう思ったあなたへ！</p>
        <br>
        <br>
        <p>↓ ↓ ↓ ↓
        <br>
        <br>
        <p><%= link_to "掃除機診断をしてみる!", cleans_sindan_path %></p>
      </div>
        
    </section>

    <section id="forth-block">
      <p class="events-title2">
        よくある質問
      </p>
      <div class="event-container">
        <div class="event">
          <p class="sitsumon1gaiyou">
            <span>Q.1</span>
            <br>
            <br>
            <br>
            <br>
            バッテリー寿命を伸ばすためには？
          </p>
          <p class="event-name-2">
            <span>A.1<br>
              <br>使い方や管理方法が大切！</span>
            <br>
            <br>
            「寿命を伸ばす」よりも「劣化を抑える」に近いかもしれません。<br>
            ポイントは２つで、「温度差」と「こまめな手入れ」です。<br>
            バッテリーの劣化には温度差が深くかかわっています。<br>
            なるべく常温の部屋で管理し、直射日光は避けましょう。<br>
            また、こまめにフィルターや内部の汚れを落としましょう。
          </p>
        </div>
        <div class="event">
          <p class="sitsumon1gaiyou">
            <span>Q.2</span>
            <br>
            <br>
            <br>
            <br>
            バッテリーの交換はどうしたらいい？
          </p>
          <p class="event-name-2">
            <span>A.2<br>
              <br>交換バッテリーは公式ストアから購入 or 量販店で取り寄せ</span>
            <br>
            <br>
            バッテリーは基本量販店での販売は行っていません。<br>
            各自、メーカー公式サイトから購入するか、<br>
            店舗で取り寄せの手続をしましょう。<br>
            交換に業者を必要とする機種があるため要確認です。
          </p>
        </div>
        <div class="event">
          <p class="sitsumon1gaiyou">
            <span>Q.3</span>
            <br>
            <br>
            <br>
            <br>
            機種の調子が悪く<br>
            量販店に持って行ったが解決しなかった
          </p>
          <p class="event-name-2">
            <span>A.3<br>
              <br>機種の調子が悪い時は、メーカー公式に問い合わせましょう</span>
            <br>
            <br>
            実は店舗の販売スタッフは故障かどうかの<br>
            判断を下す事を許可されていません。<br>
            軽い不具合であればその場で解決可能な場合がありますが、<br>
            基本的には、メーカー公式に電話等で問い合わせましょう。
          </p>
        </div>
        <div class="event">
          <p class="sitsumon1gaiyou">
            <span>Q.4</span>
            <br>
            <br>
            <br>
            <br>
            掃除機を一番お得に購入できるのはいつ？
          </p>
          <p class="event-name-2">
            <span>A.4<br>
              <br>４月 or ８～９月が狙い目？！</span>
            <br>
            <br>
            新生活シーズンの４月は家電全般がセールになることが多い。<br>
            また、型番変更が多い８～９月も狙い目です。<br>
            すなわち、既存製品が型落ちとなり値下げされます。<br>
            ※メーカーや機種によっては時期が異なる場合があります。
          </p>
        </div>
        <div class="event">
          <p class="sitsumon1gaiyou">
            <span>Q.5</span>
            <br>
            <br>
            <br>
            <br>
            コード付き掃除機比べて<br>
            コードレス掃除機は吸引力が弱い？
          </p>
          <p class="event-name-2">
            <span>A.5<br>
              <br>そんなことはありません！</span>
            <br>
            <br>
            近頃のコードレス掃除機は吸引力も強力です。<br>
            むしろ機種によってはコード付よりも強力な性能をしています。<br>
            ただし、モード切替によって稼働時間が変化してしまいます。<br>
            ※軽さ重視の機種は基本的に吸引力は弱くなります。
          </p>
        </div>
      </div>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <footer>
      <br>
      <p>Copyright © KosukeSato All Rights Reserved.</p>
      <br>
      <p>CleanUp</p>
      <br>
      <p>k__.m.10
      <br>
    </footer>
    </section>
  </body>
</html>

app/views/cleans/kensaku.html.erb
  <div class="kensakupage">
    <h1> 検 索 ペ ー ジ </h1>
  </div>
  <%= form_tag({controller:"cleans",action:"kensaku"}, method: :get) do %>
    <%= text_field_tag :search, nil, placeholder: "何をお探しですか？"%>
    <div class="tagukensaku">
      <h2>絞り込んで検索する</h2>
      <%= select_tag :tag_id,
        options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
        {
        prompt: 'タグで絞る',
        onchange: 'submit(this.form);'
        }
      %>
    </div>
  <% end %>
<div class="kontena">
  <% @cleans.each do |t| %>
    <div class="aaa" >
      <div class="post-tag">
        <% t.tags.each do |tag| %>
          <%= tag.name %>
        <%end%>
      </div>
      <div class="post">
        <div class="youso-info">
          <h2>メーカー：<%= t.maker %></h2>
          <br>
          <h2>型番：<%= t.name %></h2>
          <br>
          <h2>価格: ￥<%= t.cost %></h2>
          <div class="kensaku-kuwasiku">
            <%= link_to "詳しく", clean_path(t.id) %>
          </div>
          <div class="kensaku-like">
            <% if user_signed_in? %>
              <% if current_user.already_liked?(t) %>
                <%= link_to clean_like_path(id: t.id, cleas_id: t.id), method: :delete do %>
                  <i class="fas fa-heart"></i><%= t.likes.count %>
                <% end %>
              <% else %>
                <%= link_to clean_likes_path(id: t.id, clean_id: t.id), method: :post do %>
                  <i class="far fa-heart"></i><%= t.likes.count %>
                <% end %>
              <% end %>
            <% else %>
              <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
          </div>
        </div>
        <div class = "star">  
          <div>  
            <br>
            <br>
            <h2>総合評価：
              <span class="star-rating">
                <span class="star-rating-front" style="width: <%= getPercent(t.overall) %>%;">★★★★★</span>
                <span class="star-rating-back">★★★★★</span>
              </span> 
            </h2>
          </div>  
          <div>
            <h3>吸引力:
            <span class="star-rating">
              <span class="star-rating-front" style="width: <%= getPercent(t.power) %>%;">★★★★★</span>
              <span class="star-rating-back">★★★★★</span>
            </span>
            </h3>
          </div>
          <div>
            <h3>持続力:
            <span class="star-rating">
              <span class="star-rating-front" style="width: <%= getPercent(t.time) %>%;">★★★★★</span>
              <span class="star-rating-back">★★★★★</span>
            </span>
            </h3>
          </div>
          <div>
            <h3>手入れ:
            <span class="star-rating">
              <span class="star-rating-front" style="width: <%= getPercent(t.care) %>%;">★★★★★</span>
              <span class="star-rating-back">★★★★★</span>
            </span>
            </h3>
          </div>
        </div>
        <br>
        <div class="toukougazou">
          <%= image_tag t.image_url, size: "130x180" if t.image? %>
        </div>
        <br>
      </div>
      <% if user_signed_in? && current_user.id == t.user_id %>
        <%= button_to "削除", clean_path(t.id), method: :delete %>
      <%end%>
    </div>
  <% end %>
</div>

app/views/cleans/show.html.erb
<div class="shouhinshousainozentai">
    <h1>商品詳細</h1>
    <br>
    <div class="clean">
        <p>メーカー : <%= @clean.maker %></p>
        <br>
        <p>ジャンル : <%= @clean.genre %></p>
        <br>
        <p>型番 : <%= @clean.name %></p>
        <br>
        <p>￥<%= @clean.cost %></p>
        <br>
        <p><%= image_tag @clean.image_url, size: "250x200" if @clean.image? %></p>
        <br>
        <h3>製品の特徴</h3>
        <br>
        <p><%= @clean.about %></p>
        <br>
        <p>タグ</p>
        <% @clean.tags.each do |tag| %>
            <%= tag.name %>
        <% end %>
        <br>
        <% if user_signed_in? %>
            <% if current_user.already_liked?(@clean) %>
                <%= button_to clean_like_path(@clean), method: :delete do %>
                    <i class="fas fa-heart"></i><%= @clean.likes.count %>
                <% end %>
            <% else %>
                <%= button_to clean_likes_path(@clean), method: :post do %>
                    <i class="far fa-heart"></i><%= @clean.likes.count %>
                <% end %>
            <% end %>
        <% else %>
            <p>いいねの数 = </p><%= @clean.likes.count %>
        <% end %>
        <%= link_to "編集する", edit_clean_path(@clean.id) %>
    </div>
    <div class="comment-wrapper">
        <p>コメント一覧</p>
        <% @comments.each do |c| %>
            <div>
                <%= c.user.email unless c.user.blank? %>
                <br>
                <%= c.content %>
            </div>
            </br>
        <% end %>
        <%= form_with(model: [@clean, @comment], local: true) do |f| %>
            <%= f.text_area :content %>
            <%= button_tag type: "submit" do %>
                <i class="far fa-comments"></i> コメントする
            <% end %>   
        <% end %>
    </div>
    <%= link_to "一覧に戻る", cleans_kensaku_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>Dyson</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <script src="https://kit.fontawesome.com/c1b1cd6975.js" crossorigin="anonymous"></script>
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    
    <body>
      <header>
        <div class="home">

          <%= link_to cleans_path do %>
            <%= image_tag 'rogooo.png', alt: "Clean仮", class: "rogo" %>
          <%end%>
        </div>

        <div class="header-list">
          <div class="sindan">
            <h1><%= link_to "掃除機診断をしてみる", cleans_sindan_path %></h1>
          </div>
          <div class="new">
            <h1><% if user_signed_in? && current_user.id == 1 %>
              <%= link_to "新規投稿へ", new_clean_path %>
            <%end%></h1>
          </div>
        </div>
        
        <div class="migi">
          <div class="kensaku">
            <h1><%= link_to cleans_kensaku_path, class: "btn btn btn-secondary text-white", method: :get do %>
              <i class="fa-solid fa-magnifying-glass" style="color: #ffffff;"></i>
            <%end%></h1>
          </div>
          <div class="mypage">
            <h1>
              <% if user_signed_in? %>
                <%= link_to user_path(current_user.id), class: "btn btn btn-secondary text-white", method: :get do %>
                  <i class="fa-solid fa-user" style="color: #FFFFFF;"></i>
                <% end %>
              <% else %>
                <%= link_to new_user_registration_path, class: "btn btn btn-secondary text-white", method: :get do %>
                  <i class="fa-solid fa-user" style="color: #FFFFFF;"></i>
                <% end %>
              <% end %>
          </div>
        </div>
          </ul>
      </header>
      <main>
        <%= yield %>
      </main>
    </body>
  </html>

app/views/users/iine.html.erb
<div class="iine-zentai">
    <div class="iine-top">
        <h2>ユーザーがいいねした投稿一覧</h2>
        <h3><%= link_to "マイページトップへ", user_path(current_user.id) %></h3>
    </div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                count: resource.errors.count,
                resource: resource.class.model_name.human.downcase)
      %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "アカウントをお持ちの方はこちら", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "初回登録の方はこちらから", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードをお忘れですか?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="maipeji">
    <div class="maipejinotaitoru">
        <h1> マ イ ペ ー ジ </h1>
    </div>
</div>

<div class="second-block-mypage">
    <div class="yuzaname">
        <p>おかえりなさい<br>
        <br>
    </div>
    <div class="yuzaname2">
        <%= @user.name %>さん</p>
    </div>

    <div class="hennsyuuroguoutiine">
        <% if current_user.id == @user.id %>
            <div class="item">
                <%= link_to edit_user_registration_path, class: "btn btn btn-secondary text-white", method: :get do %>
                    <i class="fa-solid fa-pen-to-square" style="color: #ffffff;"></i>
                <% end %>
                <br>
                <br>
                <p>編集する</p>
            </div>
        <% end %>
    
        <% if user_signed_in? %>
            <div class="item">
                <%= link_to destroy_user_session_path, class: "btn btn btn-secondary text-white", method: :delete do %>
                    <i class="fa-solid fa-door-open" style="color: #ffffff;"></i>
                <%end%>
                <br>
                <br>
                <p>ログアウト</p>
            </div>
        <% else %>
            <%= link_to "新規登録", new_user_registration_path %></li>
            <%= link_to "ログイン", new_user_session_path %></li>
        <% end %></h1>

        <div class="item">
            <%= link_to :controller => "users", :action => "iine", class: "btn btn btn-secondary text-white", method: :get do %>
                <i class="fa-solid fa-heart-circle-plus" style="color: #ffffff;"></i>
            <% end %>
            <br>
            <br>
            <p>いいね履歴</p>
        </div>

        <div class="item">
            <%= link_to cleans_path, class: "btn btn btn-secondary text-white", method: :get do %>
                <i class="fa-solid fa-rotate-left" style="color: #ffffff;"></i>
            <% end %>
            <br>
            <br>
            <p>トップページに戻る</p>
        </div>
    </div>
</div>